-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module DB.Object exposing (AggregateAsset(..), AggregateBlogPost(..), AggregateColor(..), AggregateContact(..), AggregateLocation(..), AggregateProject(..), Asset(..), AssetConnection(..), AssetEdge(..), AssetPreviousValues(..), AssetSubscriptionPayload(..), BatchPayload(..), BlogPost(..), BlogPostConnection(..), BlogPostEdge(..), BlogPostPreviousValues(..), BlogPostSubscriptionPayload(..), Color(..), ColorConnection(..), ColorEdge(..), ColorPreviousValues(..), ColorSubscriptionPayload(..), Contact(..), ContactConnection(..), ContactEdge(..), ContactPreviousValues(..), ContactSubscriptionPayload(..), Location(..), LocationConnection(..), LocationEdge(..), LocationPreviousValues(..), LocationSubscriptionPayload(..), PageInfo(..), Project(..), ProjectConnection(..), ProjectEdge(..), ProjectPreviousValues(..), ProjectSubscriptionPayload(..))


type AggregateAsset
    = AggregateAsset


type AggregateBlogPost
    = AggregateBlogPost


type AggregateColor
    = AggregateColor


type AggregateContact
    = AggregateContact


type AggregateLocation
    = AggregateLocation


type AggregateProject
    = AggregateProject


type Asset
    = Asset


type AssetConnection
    = AssetConnection


type AssetEdge
    = AssetEdge


type AssetPreviousValues
    = AssetPreviousValues


type AssetSubscriptionPayload
    = AssetSubscriptionPayload


type BatchPayload
    = BatchPayload


type BlogPost
    = BlogPost


type BlogPostConnection
    = BlogPostConnection


type BlogPostEdge
    = BlogPostEdge


type BlogPostPreviousValues
    = BlogPostPreviousValues


type BlogPostSubscriptionPayload
    = BlogPostSubscriptionPayload


type Color
    = Color


type ColorConnection
    = ColorConnection


type ColorEdge
    = ColorEdge


type ColorPreviousValues
    = ColorPreviousValues


type ColorSubscriptionPayload
    = ColorSubscriptionPayload


type Contact
    = Contact


type ContactConnection
    = ContactConnection


type ContactEdge
    = ContactEdge


type ContactPreviousValues
    = ContactPreviousValues


type ContactSubscriptionPayload
    = ContactSubscriptionPayload


type Location
    = Location


type LocationConnection
    = LocationConnection


type LocationEdge
    = LocationEdge


type LocationPreviousValues
    = LocationPreviousValues


type LocationSubscriptionPayload
    = LocationSubscriptionPayload


type PageInfo
    = PageInfo


type Project
    = Project


type ProjectConnection
    = ProjectConnection


type ProjectEdge
    = ProjectEdge


type ProjectPreviousValues
    = ProjectPreviousValues


type ProjectSubscriptionPayload
    = ProjectSubscriptionPayload
