-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module DB.ScalarDecoders exposing (DateTime, Id, Long, decoders)

import DB.Scalar


type alias DateTime =
    DB.Scalar.DateTime


type alias Id =
    DB.Scalar.Id


type alias Long =
    DB.Scalar.Long


decoders : DB.Scalar.Decoders DateTime Id Long
decoders =
    DB.Scalar.defineDecoders
        { decoderDateTime = defaultDecoders.decoderDateTime
        , decoderId = defaultDecoders.decoderId
        , decoderLong = defaultDecoders.decoderLong
        }
