-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module DB.Enum.BlogPostOrderByInput exposing (BlogPostOrderByInput(..), decoder, list, toString)

import Json.Decode as Decode exposing (Decoder)


type BlogPostOrderByInput
    = Status_ASC
    | Status_DESC
    | Id_ASC
    | Id_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC
    | Title_ASC
    | Title_DESC
    | Teaser_ASC
    | Teaser_DESC
    | Body_ASC
    | Body_DESC
    | Views_ASC
    | Views_DESC


list : List BlogPostOrderByInput
list =
    [ Status_ASC, Status_DESC, Id_ASC, Id_DESC, CreatedAt_ASC, CreatedAt_DESC, UpdatedAt_ASC, UpdatedAt_DESC, Title_ASC, Title_DESC, Teaser_ASC, Teaser_DESC, Body_ASC, Body_DESC, Views_ASC, Views_DESC ]


decoder : Decoder BlogPostOrderByInput
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "status_ASC" ->
                        Decode.succeed Status_ASC

                    "status_DESC" ->
                        Decode.succeed Status_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    "title_ASC" ->
                        Decode.succeed Title_ASC

                    "title_DESC" ->
                        Decode.succeed Title_DESC

                    "teaser_ASC" ->
                        Decode.succeed Teaser_ASC

                    "teaser_DESC" ->
                        Decode.succeed Teaser_DESC

                    "body_ASC" ->
                        Decode.succeed Body_ASC

                    "body_DESC" ->
                        Decode.succeed Body_DESC

                    "views_ASC" ->
                        Decode.succeed Views_ASC

                    "views_DESC" ->
                        Decode.succeed Views_DESC

                    _ ->
                        Decode.fail ("Invalid BlogPostOrderByInput type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : BlogPostOrderByInput -> String
toString enum =
    case enum of
        Status_ASC ->
            "status_ASC"

        Status_DESC ->
            "status_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"

        Title_ASC ->
            "title_ASC"

        Title_DESC ->
            "title_DESC"

        Teaser_ASC ->
            "teaser_ASC"

        Teaser_DESC ->
            "teaser_DESC"

        Body_ASC ->
            "body_ASC"

        Body_DESC ->
            "body_DESC"

        Views_ASC ->
            "views_ASC"

        Views_DESC ->
            "views_DESC"
