-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module DB.Enum.ContactOrderByInput exposing (ContactOrderByInput(..), decoder, list, toString)

import Json.Decode as Decode exposing (Decoder)


type ContactOrderByInput
    = Status_ASC
    | Status_DESC
    | Id_ASC
    | Id_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC
    | Name_ASC
    | Name_DESC
    | Color_ASC
    | Color_DESC
    | Href_ASC
    | Href_DESC
    | Action_ASC
    | Action_DESC
    | Handle_ASC
    | Handle_DESC


list : List ContactOrderByInput
list =
    [ Status_ASC, Status_DESC, Id_ASC, Id_DESC, CreatedAt_ASC, CreatedAt_DESC, UpdatedAt_ASC, UpdatedAt_DESC, Name_ASC, Name_DESC, Color_ASC, Color_DESC, Href_ASC, Href_DESC, Action_ASC, Action_DESC, Handle_ASC, Handle_DESC ]


decoder : Decoder ContactOrderByInput
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "status_ASC" ->
                        Decode.succeed Status_ASC

                    "status_DESC" ->
                        Decode.succeed Status_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    "name_ASC" ->
                        Decode.succeed Name_ASC

                    "name_DESC" ->
                        Decode.succeed Name_DESC

                    "color_ASC" ->
                        Decode.succeed Color_ASC

                    "color_DESC" ->
                        Decode.succeed Color_DESC

                    "href_ASC" ->
                        Decode.succeed Href_ASC

                    "href_DESC" ->
                        Decode.succeed Href_DESC

                    "action_ASC" ->
                        Decode.succeed Action_ASC

                    "action_DESC" ->
                        Decode.succeed Action_DESC

                    "handle_ASC" ->
                        Decode.succeed Handle_ASC

                    "handle_DESC" ->
                        Decode.succeed Handle_DESC

                    _ ->
                        Decode.fail ("Invalid ContactOrderByInput type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : ContactOrderByInput -> String
toString enum =
    case enum of
        Status_ASC ->
            "status_ASC"

        Status_DESC ->
            "status_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"

        Name_ASC ->
            "name_ASC"

        Name_DESC ->
            "name_DESC"

        Color_ASC ->
            "color_ASC"

        Color_DESC ->
            "color_DESC"

        Href_ASC ->
            "href_ASC"

        Href_DESC ->
            "href_DESC"

        Action_ASC ->
            "action_ASC"

        Action_DESC ->
            "action_DESC"

        Handle_ASC ->
            "handle_ASC"

        Handle_DESC ->
            "handle_DESC"
