-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module DB.Object.BatchPayload exposing (count)

import DB.Object
import DB.Scalar
import DB.ScalarDecoders
import Graphql.Internal.Builder.Object as Object
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)


{-| The number of nodes that have been affected by the Batch operation.
-}
count : SelectionSet DB.ScalarDecoders.Long DB.Object.BatchPayload
count =
    Object.selectionForField "ScalarDecoders.Long" "count" [] (DB.ScalarDecoders.decoders |> DB.Scalar.unwrapDecoders |> .decoderLong)
