-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module DB.Object.ProjectsPreviousValues exposing (createdAt, description, id, link, myWork, name, status, tags, updatedAt)

import DB.Enum.Status
import DB.Object
import DB.Scalar
import DB.ScalarDecoders
import Graphql.Internal.Builder.Object as Object
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


status : SelectionSet DB.Enum.Status.Status DB.Object.ProjectsPreviousValues
status =
    Object.selectionForField "Enum.Status.Status" "status" [] DB.Enum.Status.decoder


id : SelectionSet DB.ScalarDecoders.Id DB.Object.ProjectsPreviousValues
id =
    Object.selectionForField "ScalarDecoders.Id" "id" [] (DB.ScalarDecoders.decoders |> DB.Scalar.unwrapDecoders |> .decoderId)


createdAt : SelectionSet DB.ScalarDecoders.DateTime DB.Object.ProjectsPreviousValues
createdAt =
    Object.selectionForField "ScalarDecoders.DateTime" "createdAt" [] (DB.ScalarDecoders.decoders |> DB.Scalar.unwrapDecoders |> .decoderDateTime)


updatedAt : SelectionSet DB.ScalarDecoders.DateTime DB.Object.ProjectsPreviousValues
updatedAt =
    Object.selectionForField "ScalarDecoders.DateTime" "updatedAt" [] (DB.ScalarDecoders.decoders |> DB.Scalar.unwrapDecoders |> .decoderDateTime)


name : SelectionSet String DB.Object.ProjectsPreviousValues
name =
    Object.selectionForField "String" "name" [] Decode.string


description : SelectionSet (Maybe String) DB.Object.ProjectsPreviousValues
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


myWork : SelectionSet (Maybe String) DB.Object.ProjectsPreviousValues
myWork =
    Object.selectionForField "(Maybe String)" "myWork" [] (Decode.string |> Decode.nullable)


tags : SelectionSet (List String) DB.Object.ProjectsPreviousValues
tags =
    Object.selectionForField "(List String)" "tags" [] (Decode.string |> Decode.list)


link : SelectionSet (Maybe String) DB.Object.ProjectsPreviousValues
link =
    Object.selectionForField "(Maybe String)" "link" [] (Decode.string |> Decode.nullable)
