-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module DB.Object.ProjectPreviousValues exposing (createdAt, description, id, link, myWork, name, status, tags, updatedAt)

import DB.Enum.Status
import DB.InputObject
import DB.Interface
import DB.Object
import DB.Scalar
import DB.ScalarDecoders
import DB.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


status : SelectionSet DB.Enum.Status.Status DB.Object.ProjectPreviousValues
status =
    Object.selectionForField "Enum.Status.Status" "status" [] DB.Enum.Status.decoder


id : SelectionSet DB.ScalarDecoders.Id DB.Object.ProjectPreviousValues
id =
    Object.selectionForField "ScalarDecoders.Id" "id" [] (DB.ScalarDecoders.decoders |> DB.Scalar.unwrapDecoders |> .decoderId)


createdAt : SelectionSet DB.ScalarDecoders.DateTime DB.Object.ProjectPreviousValues
createdAt =
    Object.selectionForField "ScalarDecoders.DateTime" "createdAt" [] (DB.ScalarDecoders.decoders |> DB.Scalar.unwrapDecoders |> .decoderDateTime)


updatedAt : SelectionSet DB.ScalarDecoders.DateTime DB.Object.ProjectPreviousValues
updatedAt =
    Object.selectionForField "ScalarDecoders.DateTime" "updatedAt" [] (DB.ScalarDecoders.decoders |> DB.Scalar.unwrapDecoders |> .decoderDateTime)


name : SelectionSet String DB.Object.ProjectPreviousValues
name =
    Object.selectionForField "String" "name" [] Decode.string


description : SelectionSet (Maybe String) DB.Object.ProjectPreviousValues
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


myWork : SelectionSet (Maybe String) DB.Object.ProjectPreviousValues
myWork =
    Object.selectionForField "(Maybe String)" "myWork" [] (Decode.string |> Decode.nullable)


tags : SelectionSet (List String) DB.Object.ProjectPreviousValues
tags =
    Object.selectionForField "(List String)" "tags" [] (Decode.string |> Decode.list)


link : SelectionSet (Maybe String) DB.Object.ProjectPreviousValues
link =
    Object.selectionForField "(Maybe String)" "link" [] (Decode.string |> Decode.nullable)
