-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module DB.Interface.Node exposing (Fragments, fragments, id, maybeFragments)

import DB.Interface
import DB.Object
import DB.Scalar
import DB.ScalarDecoders
import Graphql.Internal.Builder.Object as Object
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))


type alias Fragments decodesTo =
    { onAsset : SelectionSet decodesTo DB.Object.Asset
    , onBlogPost : SelectionSet decodesTo DB.Object.BlogPost
    , onProjects : SelectionSet decodesTo DB.Object.Projects
    , onColor : SelectionSet decodesTo DB.Object.Color
    , onLocation : SelectionSet decodesTo DB.Object.Location
    , onContact : SelectionSet decodesTo DB.Object.Contact
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo DB.Interface.Node
fragments selections =
    Object.exhuastiveFragmentSelection
        [ Object.buildFragment "Asset" selections.onAsset
        , Object.buildFragment "BlogPost" selections.onBlogPost
        , Object.buildFragment "Projects" selections.onProjects
        , Object.buildFragment "Color" selections.onColor
        , Object.buildFragment "Location" selections.onLocation
        , Object.buildFragment "Contact" selections.onContact
        ]


{-| Can be used to create a non-exhuastive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onAsset = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onBlogPost = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onProjects = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onColor = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onLocation = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onContact = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


{-| The id of the object.
-}
id : SelectionSet DB.ScalarDecoders.Id DB.Interface.Node
id =
    Object.selectionForField "ScalarDecoders.Id" "id" [] (DB.ScalarDecoders.decoders |> DB.Scalar.unwrapDecoders |> .decoderId)
